variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  DB_DATABASE: gestionconges
  DB_CONNECTION: mysql
  DB_USERNAME: root
  DB_PASSWORD: root
  DB_HOST: mysql
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DB_PORT: 3306

image: php:8.1

services:
  - mysql:8.0.29

stages:
  - test

cache:
  paths:
    - vendor/

test_job:
  stage: test
  before_script:
    - apt-get update && apt-get install -y default-mysql-client zip unzip git
    - docker-php-ext-install pdo pdo_mysql
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - cd back/
    - cp .env.example .env
    - php ../composer.phar install
  script:
    - ls
    - echo "CREATE DATABASE IF NOT EXISTS \`$DB_DATABASE\` ;" | mysql -h"$DB_HOST" -u"$DB_USERNAME" -p"$DB_PASSWORD"
    - mysql -h"$DB_HOST" -u"$DB_USERNAME" -p"$DB_PASSWORD" $DB_DATABASE < database/gestioncongesdump.sql
    - ./vendor/bin/phpunit tests/Unit/ValidateVacationTest.php
    - ./vendor/bin/phpunit tests/Feature/VacationRequestTest.php
